# Generated by Django 5.1.2 on 2024-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
