# Generated by Django 5.1.2 on 2024-10-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensordata_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='timestamp',
        ),
    ]
