# Generated by Django 5.1.2 on 2024-10-15 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sensordata_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='sensordata',
            name='door_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('someone at door', 'Someone at Door')], default='closed', max_length=20),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='indoor_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='outdoor_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
