# Generated by Django 5.1.2 on 2024-10-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sensordata_options_sensordata_door_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='door_status',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='indoor_light',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='outdoor_light',
        ),
    ]
